[project]
name = "python-lightweight-archipelago"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "websocket>=0.2.1",
    "websockets>=14.2",
]
